# Generated by Django 2.1.5 on 2019-05-28 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0002_auto_20190528_0746'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Master',
            new_name='Student',
        ),
    ]
