# Generated by Django 2.1.5 on 2019-05-28 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0004_auto_20190528_0826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='studentName',
            field=models.CharField(default='', max_length=250),
        ),
    ]
