# Generated by Django 2.1.5 on 2019-05-28 08:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0005_auto_20190528_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lastAttended',
            field=models.DateTimeField(auto_now=True, verbose_name='Last Class Attended'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastFeesPaid',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Last Fees Paid'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone1',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be of the form: 9876543210.', regex='^[0-9]{10}$')], verbose_name='Primary Phone No.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone2',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be of the form: 9876543210.', regex='^[0-9]{10}$')], verbose_name='Secondary Phone No.'),
        ),
        migrations.AlterField(
            model_name='student',
            name='studentName',
            field=models.CharField(default='', max_length=250, verbose_name='Student Name'),
        ),
    ]
