# Generated by Django 2.1.5 on 2019-05-28 08:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0006_auto_20190528_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone2',
            field=models.CharField(blank=True, max_length=11, validators=[django.core.validators.RegexValidator(message='Phone number must be of the form: 9876543210.', regex='^[0-9]{10}$')], verbose_name='Secondary Phone No.'),
        ),
    ]
