# Generated by Django 2.1.5 on 2019-05-28 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0009_auto_20190528_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lastAttended',
            field=models.DateField(auto_now=True, verbose_name='Last class attended'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastFeesPaid',
            field=models.DateField(auto_now_add=True, verbose_name='Last fees paid'),
        ),
    ]
