# Generated by Django 2.1.5 on 2019-05-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0010_auto_20190528_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='lastAttended',
            field=models.DateTimeField(verbose_name='Last class attended'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastFeesPaid',
            field=models.DateTimeField(verbose_name='Last fees paid'),
        ),
    ]
