# Generated by Django 2.2.1 on 2019-05-29 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0012_auto_20190529_1448'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Users',
        ),
        migrations.AlterModelOptions(
            name='student',
            options={},
        ),
    ]
