# Generated by Django 2.2.1 on 2019-05-30 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0014_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.DateField(blank=True, null=True),
        ),
    ]
