# Generated by Django 2.2.1 on 2019-05-30 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0015_auto_20190530_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.TextField(blank=True, null=True),
        ),
    ]
