# Generated by Django 2.2.1 on 2019-05-30 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registry', '0016_auto_20190530_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='storeData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(default='', max_length=100, verbose_name='Student Name')),
                ('phone_number', models.CharField(max_length=11, verbose_name='Phone Number')),
                ('password', models.CharField(max_length=30, verbose_name='Password')),
                ('no_of_class_attended', models.IntegerField()),
                ('fee_status', models.BooleanField(default=False)),
                ('validated', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
